### ISSUE TITLE
Already learned how to hack HPC clusters with Python?

### ISSUE THREAD

**Issue by N-Eichkorn** [hashkeks/advent_of_code_2022#1]
I am slightly shocked, is this a diary of a python learning kuse?

Admit it @hashkeks , this is a state trojan! ;-)

**Comment by N-Eichkorn** [comment]
What about the state Trojan? How much Bitcoin do you want?

**Comment by hashkeks** [comment]
Santa is acting independently of any state, so there is no state trojan. Doesn't mean Santa and his Elves don't wreck shit with their code. Stuxnet is what happens to naughty kids
